# Generated by Django 5.0.2 on 2024-02-29 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_rename_precio_product_price_product_is_activa_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.RenameField(
            model_name='product',
            old_name='is_activa',
            new_name='is_active',
        ),
    ]
